#cloud-config
users:
    - name: ${username}
      groups: sudo,docker
      sudo: ALL=(ALL) NOPASSWD:ALL
      hashed_passwd: ${passwd}
      lock_passwd: false
      shell: /bin/bash
      ssh-authorized-keys:
          - ${ssh_key_path}
